# Generated by Django 4.2.25 on 2025-11-04 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rbd', models.CharField(blank=True, help_text='Rol Base de Datos MINEDUC', max_length=20, null=True, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('encargado_convivencia', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_incidente', models.DateTimeField()),
                ('lugar_incidente', models.CharField(help_text='Sala, patio, baño, etc.', max_length=255)),
                ('anonimo', models.BooleanField(default=False)),
                ('reportero_externo_nombre', models.CharField(blank=True, help_text='Si el reportero no está en el sistema', max_length=255)),
                ('reportero_externo_contacto', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_investigacion', 'En Investigación'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado'), ('derivado', 'Derivado a Autoridades')], default='recibido', max_length=20)),
                ('urgencia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite_investigacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('requiere_denuncia', models.BooleanField(default=False)),
                ('fecha_denuncia', models.DateTimeField(blank=True, null=True)),
                ('numero_denuncia', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Reporte de Incidente',
                'verbose_name_plural': 'Reportes de Incidente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedidaFormativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('dialogo_reflexivo', 'Diálogo Reflexivo'), ('trabajo_comunitario', 'Trabajo Comunitario'), ('reparacion_dano', 'Reparación del Daño'), ('mediacion', 'Mediación'), ('taller_formativo', 'Taller Formativo'), ('seguimiento_psicosocial', 'Seguimiento Psicosocial'), ('compromiso_conductual', 'Compromiso Conductual'), ('otro', 'Otro')], max_length=25)),
                ('descripcion', models.TextField()),
                ('duracion_estimada_horas', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Medida Formativa',
                'verbose_name_plural': 'Medidas Formativas',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('directivo', 'Directivo'), ('apoderado', 'Apoderado'), ('encargado_convivencia', 'Encargado de Convivencia'), ('asistente', 'Asistente de la Educación'), ('administrativo', 'Administrativo')], max_length=25)),
                ('rut', models.CharField(blank=True, max_length=12)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('curso', models.CharField(blank=True, help_text='Ej: 8°A, 3° Medio', max_length=10)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colegio')),
                ('estudiantes_a_cargo', models.ManyToManyField(blank=True, to='core.perfilusuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('amonestacion_verbal', 'Amonestación Verbal'), ('amonestacion_escrita', 'Amonestación Escrita'), ('suspension_clases', 'Suspensión de Clases'), ('prohibicion_actividades', 'Prohibición de Actividades Extracurriculares'), ('condicionalidad_matricula', 'Condicionalidad de Matrícula'), ('cancelacion_matricula', 'Cancelación de Matrícula'), ('no_renovacion_matricula', 'No Renovación de Matrícula')], max_length=30)),
                ('descripcion', models.TextField()),
                ('dias_duracion', models.PositiveIntegerField(default=1, help_text='Duración en días (si aplica)')),
            ],
            options={
                'verbose_name': 'Sanción',
                'verbose_name_plural': 'Sanciones',
            },
        ),
        migrations.CreateModel(
            name='TipoIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('bullying', 'Acoso Escolar/Bullying'), ('violencia_fisica', 'Violencia Física'), ('violencia_psicologica', 'Violencia Psicológica'), ('discriminacion', 'Discriminación'), ('abuso_sexual', 'Abuso Sexual'), ('consumo_drogas', 'Consumo de Drogas/Alcohol'), ('porte_armas', 'Porte de Armas'), ('vandalismo', 'Vandalismo'), ('ciberacoso', 'Ciberacoso'), ('otro', 'Otro')], max_length=30)),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('grave', 'Grave'), ('muy_grave', 'Muy Grave')], max_length=15)),
                ('descripcion', models.TextField()),
                ('requiere_denuncia', models.BooleanField(default=False, help_text='Requiere denuncia a autoridades')),
                ('plazo_investigacion_dias', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Incidente',
                'verbose_name_plural': 'Tipos de Incidente',
            },
        ),
        migrations.CreateModel(
            name='ResolucionIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundamentacion', models.TextField(help_text='Fundamentos de la resolución')),
                ('fecha_resolucion', models.DateTimeField()),
                ('requiere_seguimiento', models.BooleanField(default=True)),
                ('fecha_seguimiento', models.DateTimeField(blank=True, null=True)),
                ('incidente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolucion', to='core.incidentreport')),
                ('medidas_formativas', models.ManyToManyField(blank=True, to='core.medidaformativa')),
                ('resuelto_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.perfilusuario')),
                ('sanciones', models.ManyToManyField(blank=True, to='core.sancion')),
            ],
            options={
                'verbose_name': 'Resolución de Incidente',
                'verbose_name_plural': 'Resoluciones de Incidente',
            },
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='asignado_a',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario__in': ['encargado_convivencia', 'directivo']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asignados', to='core.perfilusuario'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.colegio'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='estudiantes_involucrados',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuario': 'estudiante'}, related_name='incidentes_involucrado', to='core.perfilusuario'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reportero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_realizados', to='core.perfilusuario'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='testigos',
            field=models.ManyToManyField(blank=True, related_name='incidentes_testigo', to='core.perfilusuario'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='tipo_incidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoincidente'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evidencia', models.CharField(choices=[('documento', 'Documento'), ('foto', 'Fotografía'), ('video', 'Video'), ('audio', 'Audio'), ('testimonio', 'Testimonio Escrito'), ('otro', 'Otro')], default='documento', max_length=15)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('descripcion', models.CharField(max_length=255)),
                ('testimonio_texto', models.TextField(blank=True, help_text='Para testimonios escritos')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('es_confidencial', models.BooleanField(default=False)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.incidentreport')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.perfilusuario')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
            },
        ),
    ]
