# Generated by Django 5.2.7 on 2025-11-05 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('plazo_horas', models.PositiveIntegerField(default=24)),
                ('es_plazo_habiles', models.BooleanField(default=True, help_text='¿Son horas hábiles o corridas?')),
                ('responsable_rol', models.CharField(choices=[('encargado_convivencia', 'Encargado de Convivencia'), ('directivo', 'Directivo'), ('director', 'Director'), ('docente', 'Docente'), ('inspector', 'Inspector General'), ('consejo_disciplinario', 'Consejo Disciplinario'), ('equipo_convivencia', 'Equipo de Convivencia')], max_length=25)),
                ('acciones_requeridas', models.TextField(help_text='Descripción de las acciones a realizar en esta etapa')),
                ('documentos_requeridos', models.TextField(blank=True, help_text='Documentos que se deben generar/adjuntar')),
                ('es_obligatoria', models.BooleanField(default=True)),
                ('permite_anonimo', models.BooleanField(default=True, help_text='¿Se puede ejecutar con denuncia anónima?')),
                ('accion_si_anonimo', models.CharField(choices=[('normal', 'Proceso Normal'), ('modificada', 'Proceso Modificado'), ('omitir', 'Omitir Esta Etapa')], default='normal', max_length=20)),
                ('descripcion_anonimo', models.TextField(blank=True, help_text='Descripción alternativa para casos anónimos')),
            ],
            options={
                'verbose_name': 'Etapa de Protocolo',
                'verbose_name_plural': 'Etapas de Protocolo',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='justificacion_anonimato',
            field=models.TextField(blank=True, help_text='¿Por qué solicita anonimato?'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='nivel_anonimato',
            field=models.CharField(choices=[('publico', 'Público - Mi identidad puede ser conocida'), ('restringido', 'Restringido - Solo autoridades del colegio'), ('confidencial', 'Confidencial - Solo Encargado de Convivencia'), ('judicial', 'Judicial - Solo para efectos legales')], default='publico', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='solicita_anonimato',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProtocoloProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('grave', 'Grave'), ('muy_grave', 'Muy Grave')], max_length=15)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('plazo_total_dias', models.PositiveIntegerField(default=15, help_text='Plazo máximo total del proceso')),
                ('requiere_aprobacion_director', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colegio')),
            ],
            options={
                'verbose_name': 'Protocolo de Proceso',
                'verbose_name_plural': 'Protocolos de Proceso',
                'unique_together': {('colegio', 'gravedad')},
            },
        ),
        migrations.CreateModel(
            name='ProcesoIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('en_curso', 'En Curso'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='iniciado', max_length=15)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('etapa_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.etapaprotocolo')),
                ('incidente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proceso', to='core.incidentreport')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.protocoloproceso')),
            ],
            options={
                'verbose_name': 'Proceso de Incidente',
                'verbose_name_plural': 'Procesos de Incidente',
            },
        ),
        migrations.AddField(
            model_name='etapaprotocolo',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='core.protocoloproceso'),
        ),
        migrations.CreateModel(
            name='AccesoIdentidadDenunciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acceso', models.CharField(choices=[('automatico', 'Acceso Automático por Rol'), ('otorgado', 'Acceso Otorgado Específicamente'), ('judicial', 'Acceso por Orden Judicial'), ('emergencia', 'Acceso de Emergencia')], max_length=15)),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('fecha_primer_acceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('numero_accesos', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos_autorizados', to='core.perfilusuario')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_identidad', to='core.incidentreport')),
                ('usuario_autorizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perfilusuario')),
            ],
            options={
                'verbose_name': 'Acceso a Identidad de Denunciante',
                'verbose_name_plural': 'Accesos a Identidad de Denunciante',
                'unique_together': {('incidente', 'usuario_autorizado')},
            },
        ),
        migrations.CreateModel(
            name='EjecucionEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('omitida', 'Omitida'), ('vencida', 'Vencida')], default='pendiente', max_length=15)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('archivos_adjuntos', models.FileField(blank=True, null=True, upload_to='etapas/')),
                ('modificada_por_anonimato', models.BooleanField(default=False)),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.perfilusuario')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etapaprotocolo')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='core.procesoincidente')),
            ],
            options={
                'verbose_name': 'Ejecución de Etapa',
                'verbose_name_plural': 'Ejecuciones de Etapa',
                'unique_together': {('proceso', 'etapa')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='etapaprotocolo',
            unique_together={('protocolo', 'orden')},
        ),
        migrations.CreateModel(
            name='ReglasAnonimato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_anonimato', models.CharField(choices=[('publico', 'Público - Mi identidad puede ser conocida'), ('restringido', 'Restringido - Solo autoridades del colegio'), ('confidencial', 'Confidencial - Solo Encargado de Convivencia'), ('judicial', 'Judicial - Solo para efectos legales')], max_length=20)),
                ('roles_con_acceso', models.TextField(help_text='Roles separados por coma que pueden ver la identidad')),
                ('requiere_aprobacion', models.BooleanField(default=False, help_text='¿Requiere aprobación adicional?')),
                ('notificar_acceso', models.BooleanField(default=True, help_text='¿Notificar al denunciante sobre accesos?')),
                ('plazo_acceso_horas', models.PositiveIntegerField(default=24, help_text='Horas máximas para mantener acceso')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colegio')),
            ],
            options={
                'verbose_name': 'Regla de Anonimato',
                'verbose_name_plural': 'Reglas de Anonimato',
                'unique_together': {('colegio', 'nivel_anonimato')},
            },
        ),
    ]
