# Generated by Django 5.2.7 on 2025-11-07 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_denunciaobligatoria_denunciante_institucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoincidente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoincidente',
            name='colegio',
            field=models.ForeignKey(blank=True, help_text='Colegio específico. NULL = aplica a todos los colegios (categorías base)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.colegio'),
        ),
        migrations.AddField(
            model_name='tipoincidente',
            name='es_categoria_legal',
            field=models.BooleanField(default=False, help_text='Indica si es una categoría definida por normativa legal (no editable)'),
        ),
        migrations.AddField(
            model_name='tipoincidente',
            name='protocolo_especifico',
            field=models.TextField(blank=True, help_text='Protocolo específico del colegio para este tipo de incidente'),
        ),
        migrations.AddField(
            model_name='tipoincidente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='tipoincidente',
            unique_together={('nombre', 'colegio')},
        ),
        migrations.AddIndex(
            model_name='tipoincidente',
            index=models.Index(fields=['categoria', 'colegio'], name='core_tipoin_categor_a04183_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoincidente',
            index=models.Index(fields=['es_categoria_legal'], name='core_tipoin_es_cate_ddf514_idx'),
        ),
    ]
